export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTION';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTION_SUCCESS';
export const FETCH_TRANSACTIONS_FAILURE = 'FETCH_TRANSACTION_FAILURE';

export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAILURE = 'CREATE_TRANSACTION_FAILURE';